// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.AccountHolderImport;
using LocalGovIMSClient.Api.AccountHolders;
using LocalGovIMSClient.Api.FundMetadata;
using LocalGovIMSClient.Api.Funds;
using LocalGovIMSClient.Api.MethodOfPayments;
using LocalGovIMSClient.Api.Payments;
using LocalGovIMSClient.Api.PendingTransaction;
using LocalGovIMSClient.Api.PendingTransactions;
using LocalGovIMSClient.Api.ProcessedTransactions;
using LocalGovIMSClient.Api.Suspense;
using LocalGovIMSClient.Api.TransactionImport;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalGovIMSClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AccountHolderImport property</summary>
        public global::LocalGovIMSClient.Api.AccountHolderImport.AccountHolderImportRequestBuilder AccountHolderImport
        {
            get => new global::LocalGovIMSClient.Api.AccountHolderImport.AccountHolderImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AccountHolders property</summary>
        public global::LocalGovIMSClient.Api.AccountHolders.AccountHoldersRequestBuilder AccountHolders
        {
            get => new global::LocalGovIMSClient.Api.AccountHolders.AccountHoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The FundMetadata property</summary>
        public global::LocalGovIMSClient.Api.FundMetadata.FundMetadataRequestBuilder FundMetadata
        {
            get => new global::LocalGovIMSClient.Api.FundMetadata.FundMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Funds property</summary>
        public global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder Funds
        {
            get => new global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MethodOfPayments property</summary>
        public global::LocalGovIMSClient.Api.MethodOfPayments.MethodOfPaymentsRequestBuilder MethodOfPayments
        {
            get => new global::LocalGovIMSClient.Api.MethodOfPayments.MethodOfPaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Payments property</summary>
        public global::LocalGovIMSClient.Api.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::LocalGovIMSClient.Api.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PendingTransaction property</summary>
        public global::LocalGovIMSClient.Api.PendingTransaction.PendingTransactionRequestBuilder PendingTransaction
        {
            get => new global::LocalGovIMSClient.Api.PendingTransaction.PendingTransactionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PendingTransactions property</summary>
        public global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder PendingTransactions
        {
            get => new global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ProcessedTransactions property</summary>
        public global::LocalGovIMSClient.Api.ProcessedTransactions.ProcessedTransactionsRequestBuilder ProcessedTransactions
        {
            get => new global::LocalGovIMSClient.Api.ProcessedTransactions.ProcessedTransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Suspense property</summary>
        public global::LocalGovIMSClient.Api.Suspense.SuspenseRequestBuilder Suspense
        {
            get => new global::LocalGovIMSClient.Api.Suspense.SuspenseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TransactionImport property</summary>
        public global::LocalGovIMSClient.Api.TransactionImport.TransactionImportRequestBuilder TransactionImport
        {
            get => new global::LocalGovIMSClient.Api.TransactionImport.TransactionImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
