// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.ProcessedTransactions.Item.ProcessFee;
using LocalGovIMSClient.Api.ProcessedTransactions.Item.UpdateCardDetails;
using LocalGovIMSClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LocalGovIMSClient.Api.ProcessedTransactions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ProcessedTransactions\{reference}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithReferenceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ProcessFee property</summary>
        public global::LocalGovIMSClient.Api.ProcessedTransactions.Item.ProcessFee.ProcessFeeRequestBuilder ProcessFee
        {
            get => new global::LocalGovIMSClient.Api.ProcessedTransactions.Item.ProcessFee.ProcessFeeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdateCardDetails property</summary>
        public global::LocalGovIMSClient.Api.ProcessedTransactions.Item.UpdateCardDetails.UpdateCardDetailsRequestBuilder UpdateCardDetails
        {
            get => new global::LocalGovIMSClient.Api.ProcessedTransactions.Item.UpdateCardDetails.UpdateCardDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.ProcessedTransactions.Item.WithReferenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReferenceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ProcessedTransactions/{reference}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.ProcessedTransactions.Item.WithReferenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReferenceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ProcessedTransactions/{reference}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::LocalGovIMSClient.Models.ProcessedTransactionModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::LocalGovIMSClient.Models.ProcessedTransactionModel?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::LocalGovIMSClient.Models.ProcessedTransactionModel> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::LocalGovIMSClient.Models.ProcessedTransactionModel>(requestInfo, global::LocalGovIMSClient.Models.ProcessedTransactionModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.ProcessedTransactions.Item.WithReferenceItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LocalGovIMSClient.Api.ProcessedTransactions.Item.WithReferenceItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LocalGovIMSClient.Api.ProcessedTransactions.Item.WithReferenceItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
