// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.FundMetadata.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalGovIMSClient.Api.FundMetadata.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\FundMetadata\{key}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithKeyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LocalGovIMSClient.api.FundMetadata.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.FundMetadata.Item.Item.WithFundCodeItemRequestBuilder"/></returns>
        public global::LocalGovIMSClient.Api.FundMetadata.Item.Item.WithFundCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fundCode", position);
                return new global::LocalGovIMSClient.Api.FundMetadata.Item.Item.WithFundCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.FundMetadata.Item.WithKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithKeyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/FundMetadata/{key}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.FundMetadata.Item.WithKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithKeyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/FundMetadata/{key}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
