// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LocalGovIMSClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountHolderModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AccountReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountReference { get; set; }
#nullable restore
#else
        public string AccountReference { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AddressLine1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine1 { get; set; }
#nullable restore
#else
        public string AddressLine1 { get; set; }
#endif
        /// <summary>The AddressLine2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine2 { get; set; }
#nullable restore
#else
        public string AddressLine2 { get; set; }
#endif
        /// <summary>The AddressLine3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine3 { get; set; }
#nullable restore
#else
        public string AddressLine3 { get; set; }
#endif
        /// <summary>The AddressLine4 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine4 { get; set; }
#nullable restore
#else
        public string AddressLine4 { get; set; }
#endif
        /// <summary>The CurrentBalance property</summary>
        public double? CurrentBalance { get; set; }
        /// <summary>The Forename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Forename { get; set; }
#nullable restore
#else
        public string Forename { get; set; }
#endif
        /// <summary>The FundCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FundCode { get; set; }
#nullable restore
#else
        public string FundCode { get; set; }
#endif
        /// <summary>The FundMessageId property</summary>
        public int? FundMessageId { get; set; }
        /// <summary>The PeriodCredit property</summary>
        public double? PeriodCredit { get; set; }
        /// <summary>The PeriodDebit property</summary>
        public double? PeriodDebit { get; set; }
        /// <summary>The Postcode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Postcode { get; set; }
#nullable restore
#else
        public string Postcode { get; set; }
#endif
        /// <summary>The RecordType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordType { get; set; }
#nullable restore
#else
        public string RecordType { get; set; }
#endif
        /// <summary>The Surname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Surname { get; set; }
#nullable restore
#else
        public string Surname { get; set; }
#endif
        /// <summary>The Title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The UserField1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserField1 { get; set; }
#nullable restore
#else
        public string UserField1 { get; set; }
#endif
        /// <summary>The UserField2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserField2 { get; set; }
#nullable restore
#else
        public string UserField2 { get; set; }
#endif
        /// <summary>The UserField3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserField3 { get; set; }
#nullable restore
#else
        public string UserField3 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Models.AccountHolderModel"/> and sets the default values.
        /// </summary>
        public AccountHolderModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LocalGovIMSClient.Models.AccountHolderModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LocalGovIMSClient.Models.AccountHolderModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LocalGovIMSClient.Models.AccountHolderModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountReference", n => { AccountReference = n.GetStringValue(); } },
                { "AddressLine1", n => { AddressLine1 = n.GetStringValue(); } },
                { "AddressLine2", n => { AddressLine2 = n.GetStringValue(); } },
                { "AddressLine3", n => { AddressLine3 = n.GetStringValue(); } },
                { "AddressLine4", n => { AddressLine4 = n.GetStringValue(); } },
                { "CurrentBalance", n => { CurrentBalance = n.GetDoubleValue(); } },
                { "Forename", n => { Forename = n.GetStringValue(); } },
                { "FundCode", n => { FundCode = n.GetStringValue(); } },
                { "FundMessageId", n => { FundMessageId = n.GetIntValue(); } },
                { "PeriodCredit", n => { PeriodCredit = n.GetDoubleValue(); } },
                { "PeriodDebit", n => { PeriodDebit = n.GetDoubleValue(); } },
                { "Postcode", n => { Postcode = n.GetStringValue(); } },
                { "RecordType", n => { RecordType = n.GetStringValue(); } },
                { "Surname", n => { Surname = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "UserField1", n => { UserField1 = n.GetStringValue(); } },
                { "UserField2", n => { UserField2 = n.GetStringValue(); } },
                { "UserField3", n => { UserField3 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountReference", AccountReference);
            writer.WriteStringValue("AddressLine1", AddressLine1);
            writer.WriteStringValue("AddressLine2", AddressLine2);
            writer.WriteStringValue("AddressLine3", AddressLine3);
            writer.WriteStringValue("AddressLine4", AddressLine4);
            writer.WriteDoubleValue("CurrentBalance", CurrentBalance);
            writer.WriteStringValue("Forename", Forename);
            writer.WriteStringValue("FundCode", FundCode);
            writer.WriteIntValue("FundMessageId", FundMessageId);
            writer.WriteDoubleValue("PeriodCredit", PeriodCredit);
            writer.WriteDoubleValue("PeriodDebit", PeriodDebit);
            writer.WriteStringValue("Postcode", Postcode);
            writer.WriteStringValue("RecordType", RecordType);
            writer.WriteStringValue("Surname", Surname);
            writer.WriteStringValue("Title", Title);
            writer.WriteStringValue("UserField1", UserField1);
            writer.WriteStringValue("UserField2", UserField2);
            writer.WriteStringValue("UserField3", UserField3);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
