// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LocalGovIMSClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SuspenseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AccountNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Amount property</summary>
        public double? Amount { get; set; }
        /// <summary>The CreatedAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The ImportId property</summary>
        public int? ImportId { get; set; }
        /// <summary>The Narrative property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Narrative { get; set; }
#nullable restore
#else
        public string Narrative { get; set; }
#endif
        /// <summary>The Notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The ProcessId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProcessId { get; set; }
#nullable restore
#else
        public string ProcessId { get; set; }
#endif
        /// <summary>The TransactionDate property</summary>
        public DateTimeOffset? TransactionDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Models.SuspenseModel"/> and sets the default values.
        /// </summary>
        public SuspenseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LocalGovIMSClient.Models.SuspenseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LocalGovIMSClient.Models.SuspenseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LocalGovIMSClient.Models.SuspenseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountNumber", n => { AccountNumber = n.GetStringValue(); } },
                { "Amount", n => { Amount = n.GetDoubleValue(); } },
                { "CreatedAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "ImportId", n => { ImportId = n.GetIntValue(); } },
                { "Narrative", n => { Narrative = n.GetStringValue(); } },
                { "Notes", n => { Notes = n.GetStringValue(); } },
                { "ProcessId", n => { ProcessId = n.GetStringValue(); } },
                { "TransactionDate", n => { TransactionDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountNumber", AccountNumber);
            writer.WriteDoubleValue("Amount", Amount);
            writer.WriteDateTimeOffsetValue("CreatedAt", CreatedAt);
            writer.WriteIntValue("Id", Id);
            writer.WriteIntValue("ImportId", ImportId);
            writer.WriteStringValue("Narrative", Narrative);
            writer.WriteStringValue("Notes", Notes);
            writer.WriteStringValue("ProcessId", ProcessId);
            writer.WriteDateTimeOffsetValue("TransactionDate", TransactionDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
