// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.PendingTransaction.Item.Authorise;
using LocalGovIMSClient.Api.PendingTransaction.Item.ProcessPayment;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalGovIMSClient.Api.PendingTransaction.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\PendingTransaction\{reference}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithReferenceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Authorise property</summary>
        public global::LocalGovIMSClient.Api.PendingTransaction.Item.Authorise.AuthoriseRequestBuilder Authorise
        {
            get => new global::LocalGovIMSClient.Api.PendingTransaction.Item.Authorise.AuthoriseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ProcessPayment property</summary>
        public global::LocalGovIMSClient.Api.PendingTransaction.Item.ProcessPayment.ProcessPaymentRequestBuilder ProcessPayment
        {
            get => new global::LocalGovIMSClient.Api.PendingTransaction.Item.ProcessPayment.ProcessPaymentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.PendingTransaction.Item.WithReferenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReferenceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/PendingTransaction/{reference}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.PendingTransaction.Item.WithReferenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReferenceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/PendingTransaction/{reference}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
