// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.Funds.Item;
using LocalGovIMSClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LocalGovIMSClient.Api.Funds
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Funds
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FundsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LocalGovIMSClient.api.Funds.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.Funds.Item.WithFundCodeItemRequestBuilder"/></returns>
        public global::LocalGovIMSClient.Api.Funds.Item.WithFundCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fundCode", position);
                return new global::LocalGovIMSClient.Api.Funds.Item.WithFundCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FundsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Funds{?fundCode*,fundName*,isDisabled*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FundsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Funds{?fundCode*,fundName*,isDisabled*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::LocalGovIMSClient.Models.FundModel&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::LocalGovIMSClient.Models.FundModel>?> GetAsync(Action<RequestConfiguration<global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::LocalGovIMSClient.Models.FundModel>> GetAsync(Action<RequestConfiguration<global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::LocalGovIMSClient.Models.FundModel>(requestInfo, global::LocalGovIMSClient.Models.FundModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LocalGovIMSClient.Api.Funds.FundsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class FundsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fundCode")]
            public string? FundCode { get; set; }
#nullable restore
#else
            [QueryParameter("fundCode")]
            public string FundCode { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fundName")]
            public string? FundName { get; set; }
#nullable restore
#else
            [QueryParameter("fundName")]
            public string FundName { get; set; }
#endif
            [QueryParameter("isDisabled")]
            public bool? IsDisabled { get; set; }
        }
    }
}
#pragma warning restore CS0618
