// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.PendingTransactions.Item;
using LocalGovIMSClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace LocalGovIMSClient.Api.PendingTransactions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\PendingTransactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PendingTransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LocalGovIMSClient.api.PendingTransactions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.PendingTransactions.Item.WithReferenceItemRequestBuilder"/></returns>
        public global::LocalGovIMSClient.Api.PendingTransactions.Item.WithReferenceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("reference", position);
                return new global::LocalGovIMSClient.Api.PendingTransactions.Item.WithReferenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PendingTransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/PendingTransactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PendingTransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/PendingTransactions", rawUrl)
        {
        }
        /// <returns>A List&lt;global::LocalGovIMSClient.Models.PendingTransactionModel&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::LocalGovIMSClient.Models.PendingTransactionModel>?> PostAsync(global::LocalGovIMSClient.Models.PendingTransactionModel body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::LocalGovIMSClient.Models.PendingTransactionModel>> PostAsync(global::LocalGovIMSClient.Models.PendingTransactionModel body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::LocalGovIMSClient.Models.PendingTransactionModel>(requestInfo, global::LocalGovIMSClient.Models.PendingTransactionModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::LocalGovIMSClient.Models.PendingTransactionModel body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::LocalGovIMSClient.Models.PendingTransactionModel body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::LocalGovIMSClient.Api.PendingTransactions.PendingTransactionsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
