// <auto-generated/>
#pragma warning disable CS0618
using LocalGovIMSClient.Api.FundMetadata.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalGovIMSClient.Api.FundMetadata
{
    /// <summary>
    /// Builds and executes requests for operations under \api\FundMetadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FundMetadataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LocalGovIMSClient.api.FundMetadata.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LocalGovIMSClient.Api.FundMetadata.Item.WithKeyItemRequestBuilder"/></returns>
        public global::LocalGovIMSClient.Api.FundMetadata.Item.WithKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key", position);
                return new global::LocalGovIMSClient.Api.FundMetadata.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.FundMetadata.FundMetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FundMetadataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/FundMetadata", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalGovIMSClient.Api.FundMetadata.FundMetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FundMetadataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/FundMetadata", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
